# Generated by Django 4.0.3 on 2022-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(default='Morbi turpis nisl, auctor ut nisl vel, pellentesque euismod nunc nunc accumsan imperdiet.')),
                ('location', models.CharField(default='McLean, VA', max_length=100)),
                ('client', models.CharField(default='Pransbay Powers Authority', max_length=100)),
                ('architect', models.CharField(default='Dlarke Pelli Incorp', max_length=100)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/projects/')),
                ('categories', models.ManyToManyField(to='home.category')),
            ],
        ),
    ]
