# Generated by Django 4.0.3 on 2022-08-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news_pricingfeatures_solution_team_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
