# Generated by Django 4.0.3 on 2022-08-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(default='Nats Stenman began his career in construction with boots on the ground')),
                ('n_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.news')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='news',
            name='comments_all',
            field=models.ManyToManyField(to='home.comment'),
        ),
    ]
