# Generated by Django 4.0.3 on 2022-08-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_news_comments_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='n_name',
        ),
    ]
